### ISSUE TITLE
Demo not working on ios

### ISSUE THREAD

**Issue by yogeshcerebrate** [allenRoyston/ngCroppie#1]
I tried demo page on safari but it continuously gives an error saying "Cross-origin image load denied by Cross-Origin Resource Sharing policy" please refer image below
<img width="1280" alt="safari_error" src="https://cloud.githubusercontent.com/assets/7901632/13670763/bf578e2c-e6f1-11e5-98e9-70d643aa966b.png">
can you suggest me how to fix this issue?

**Comment by bionetmarco** [comment]
This was a croppie issue. You can update the croppie source code by including [Croppie v2.1.1](https://github.com/Foliotek/Croppie/blob/master/croppie.js), and removing v1.0.3 from ng-croppie.js.

**Comment by allenRoyston** [comment]
Hey thanks!  I'll make sure to update this source code when I get the chance =D

**Comment by gopika10** [comment]
Hey Allen, can you update your code for supporting it in safari.

**Comment by orif-jr** [comment]
This issue is resolved by [v1.2.1](https://github.com/allenRoyston/ngCroppie/releases/tag/1.2.1)
Tested on Safari 11
