### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by fireole** [allenRoyston/ngCroppie#10]
this piece keeps repeating after I load a base64 image into croppie.  It just goes and never stops.

              // create new croppie and settime for updates
              var c = new Croppie(elem[0], options);
              var intervalID = window.setInterval(function () {
                  c.result('canvas').then(function (img) {
                      scope.$apply(function () {
                          scope.ngModel = img
                      })
                  })
              }, 250);

My html:

            <ng-croppie src="vm.croppieImage"
                        ng-model="vm.outputImage"
                        update="vm.onUpdate"
                        boundry="{w: 400, h: 400}"
                        viewport="{w: 300, h:300}"
                        mousezoom="true"
                        zoom="true">
            </ng-croppie>

**Comment by allenRoyston** [comment]
Yeah, that's actually not a bug.  That interval is what's updating that preview image.  The interval will destroy itself once you've made finalized your seleciton.

**Comment by fireole** [comment]
so if I let it sit there for about a minute, then in console then i will get XXX GET requests.  

I used your site to reproduce just to make sure it wasn't something I was doing on my end. Just uploaded a random picture using the select option and not one of the Load Image 1 or 2 options.

![image](https://cloud.githubusercontent.com/assets/985103/16677283/e80e4636-4488-11e6-9135-dbe4814ede5d.png)

**Comment by allenRoyston** [comment]
It seems like a lot, yes, but it's not actually doing any GET requests.  The amount of overhead is pretty low for a desktop.  It's just more or less calling itself.  You can change the interval in the directive (I actually changed it from 0 to 250 for this reason), but the preview starts to look choppy.  There's really no way around this as far as I know, but if you have a better method I'd love to see it.

**Comment by fireole** [comment]
Ok, no problem and just wanted to make sure.   I suppose I look at it from if I hand my app off to some other developer and they are in there debugging it and then see the request keep going, they probably would question me on it.  

I will have to ponder on it to see.  I like what you have done and this is exactly what I have been looking for.  I paired it with ng-file-upload to reduce some file size and others and then send it into ng-croppie.  Once I get this then ship off to cloudinary.   

So thanks for the plugin!  

Now if I can just figure that last part.   :)

**Comment by allenRoyston** [comment]
Hey no problem!  But seriously if you can think of a better way to handle it, I'm totally open to changing it.  I know it looks weird with all those "requests" but I just don't know if there's another way to handle it.  Take care =D
