### ISSUE TITLE
Missing Version Number in bower.json seems to break my Grunt Tasks

### ISSUE THREAD

**Issue by MikeSav** [allenRoyston/ngCroppie#15]
Hi there, I've noticed that a wildcard is inserted into the bower.json when I install ngCroppie using the terminal. This seems to break my Grunt tasks contained in my grunt.js. No registered tasks are recognisable or listed. When I remove `"ngCroppie": "*"`from Bower and update / install, my tasks in Grunt return. Adding `"ngCroppie": "1.0.0"` to my Bower file does not work as we get 

> bower ENORESTARGET  No tag found that was able to satisfy 1.0.0

Would it be possible to insert a version number?

**Comment by orif-jr** [comment]
@MikeSav Version 1.0.0 has been released.
