### ISSUE TITLE
Rotation feature is not included?

### ISSUE THREAD

**Issue by orif-jr** [allenRoyston/ngCroppie#26]
Hi there,
we are currently using [latest commit](https://github.com/allenRoyston/ngCroppie/commit/ab9e64cf6aec15dbcba02a1ca48620f1a74d8484) which is still missing image rotation functionality. The topic is actually discussed [here](https://github.com/allenRoyston/ngCroppie/issues/4). So, are you planing to include it?
Would be great to have it soon :)

**Comment by allenRoyston** [comment]
Hey, sorry I haven't really been maintaining this module as well as I should have.  I have a full time job and side projects I'm working on and this one kind of fell to the wayside.  Apologies in advance, but I probably won't get around to updating this any time soon :(

**Comment by orif-jr** [comment]
I actually added some changes to your code and it works great with rotation functionality :)
So, if you include me to the list of contributors (or maybe as co-authors :D just kidding) I would ne happy to share my code.

**Comment by allenRoyston** [comment]
Hey orif-jr, sorry I didn't get around to this sooner.  (Ugh work).  If you have a pull-request you'd like to submit, I'll happily merge it in and add you to the list of credits.  Sorry again about the delay.

**Comment by orif-jr** [comment]
Great! Just created a [new pull](https://github.com/allenRoyston/ngCroppie/pull/27) request, which contains code changes/ enhancement and updated readme file.
Btw, it makes sence to release first official version now, because until now ngCroppie is available only with commit hashes (and it's disaster). I can to that also as soon as you give me access to the repo. This way I could contribute better and things could go faster ;)
