### ISSUE TITLE
Keep Reading File

### ISSUE THREAD

**Issue by YounianC** [allenRoyston/ngCroppie#3]
Live Demo:
if you choose a local pic , the js code will keep reading data from local file (pc) which is bad for performance and the online pic doesn't , is it necessary ?
thx !
@allenRoyston

**Comment by Neo-89** [comment]
+1

**Comment by allenRoyston** [comment]
Hi, great question.  Sorry it took so long to get back to you.  

So the demo is using an older version that didn't destroy the setInterval when the component was finished.  That was patched.  The current version that's in the repo should work correctly.

As for the "is it necessary?"  Well, unfortunately yes.  I'm not a huge fan of using timers either but what makes the whole thing work is the canvas renders the image, and then some logic runs on the interval to check the data, then puts that into the image tag.  So can it be done without the timer?  Well, *maybe*, but not likely.  If anybody has a more elegant solution I'm all ears.  =D
