### ISSUE TITLE
Error angular.min.js:107 ReferenceError: Croppie is not defined

### ISSUE THREAD

**Issue by akiselev87** [allenRoyston/ngCroppie#32]
Got angularjs 1.4.8 and made an installation of ngCroppie:
1) Made a copy of js files to my lib, set link to ng-croppie.js:
`<script src="../lib/js/ng-croppie.js"></script>`

2) Added code to my html page:
```
<td rowspan="12" style="vertical-align: baseline;">
<headertext>Avatar</headertext><br>
<ng-croppie   src="inputImage"
   ng-model='outputImage'>
</ng-croppie>
</td>
```

3) Added code to my main js:

```
angular.module('scopeRegistration', ['toaster','ngAnimate', 'ngCroppie']).
controller('RegController', ['$scope', '$http','toaster', 
function($scope, $http, toaster) {

```
and
```
$scope.outputImage = null;
$scope.inputImage = "path/to/image.png"
$scope.onUpdate = function(data){
    // runs whenever there's a change
}
```
and I got a console error on page load (chrome 57.0):

> angular.min.js:107 ReferenceError: Croppie is not defined
>     at link (http://192.168.16.66:8182/ChatGUINoSQL/lib/js/ng-croppie.js:91:29)
>     at http://192.168.16.66:8182/ChatGUINoSQL/lib/js/angular.min.js:73:236
>     at ea (http://192.168.16.66:8182/ChatGUINoSQL/lib/js/angular.min.js:73:293)
>     at D (http://192.168.16.66:8182/ChatGUINoSQL/lib/js/angular.min.js:62:190)
>     at g (http://192.168.16.66:8182/ChatGUINoSQL/lib/js/angular.min.js:55:105)
>     at g (http://192.168.16.66:8182/ChatGUINoSQL/lib/js/angular.min.js:55:122)
>     at g (http://192.168.16.66:8182/ChatGUINoSQL/lib/js/angular.min.js:55:122)
>     at g (http://192.168.16.66:8182/ChatGUINoSQL/lib/js/angular.min.js:55:122)
>     at g (http://192.168.16.66:8182/ChatGUINoSQL/lib/js/angular.min.js:55:122)
>     at D (http://192.168.16.66:8182/ChatGUINoSQL/lib/js/angular.min.js:62:134) <ng-croppie src="inputImage" ng-model="outputImage" class="ng-pristine ng-untouched ng-valid ng-isolate-scope">

could you please clarify how to fix this?

**Comment by stasinua** [comment]
Hello @akiselev87 ! Thanks for your report. 
For now the solution is to manually install Croppie.js and link its croppie.js to your project.

**Comment by orif-jr** [comment]
Since Croppie.js is now included as dependencies the issue can be closed.
