### ISSUE TITLE
Infinite img call

### ISSUE THREAD

**Issue by Chrumo** [allenRoyston/ngCroppie#33]
When I upload photo from my file system, ngCroppie start infinite loop for that resource. Even after closing modal window(in which is ngCroppie) its still requesting that same base64 resource. Appended picture is Network developer tool inside Chromium browser on Ubuntu.

It stops requesting after I load image 1 or image 2 from the demo.

![screenshot from 2017-06-07 17-39-39](https://user-images.githubusercontent.com/5585677/26887536-88358f8a-4ba8-11e7-91e8-603989c54925.png)

**Comment by orifn** [comment]
@Chrumo are you still facing this issue?
have a try with [v1.2.1](https://github.com/allenRoyston/ngCroppie/releases/tag/1.2.1) and let us know about the results.

**Comment by akagabi** [comment]
Still have it. Any suggestions on how to solve it?

**Comment by stasinua** [comment]
@fermijs It is an issue since the beginning of this library. Before v1 I'd solved it by placing control "setInterval"(which holds img requests) in "mousedown" event. You can find more details in my pull request:
https://github.com/allenRoyston/ngCroppie/pull/24

Maybe it would help.
