### ISSUE TITLE
Output Image Size

### ISSUE THREAD

**Issue by mark2411** [allenRoyston/ngCroppie#34]
Having a bit of an issue with this, the size of the output image doesn't seem to be constant. It should be the same size as the Viewport, however it changes depending on how far into the photo I zoom. If I zoom in far, the size of the output photo shrinks, if I zoom back out again it grows.

Any ideas?

**Comment by dilbatch** [comment]
Yea. The weird part is that there is no such effect in Demo -  any specific options need to be checked?

**Comment by dilbatch** [comment]
Any comment/improvement on that issue?

**Comment by dilbatch** [comment]
It seems the generate controls, html, divs are not the same as that on the demo 
![image](https://user-images.githubusercontent.com/7666257/28501966-b580092c-6ff0-11e7-9839-c79960228116.png)

**Comment by dilbatch** [comment]
Ok that comes from the orientation. i mean to use canvas or img

**Comment by dilbatch** [comment]
So the problem with 
" the size of the output image doesn't seem to be constant. It should be the same size as the Viewport, however it changes depending on how far into the photo I zoom. If I zoom in far, the size of the output photo shrinks, if I zoom back out again it grows."  stays.

Any ideas?

**Comment by dilbatch** [comment]
Ok   I uninstall and install ng croppie again from bower and it works now
just in bower list  the croppie is 2.5.0 as:
├─┬ ngCroppie#1.0.3
│ └── croppie#2.5.0 incompatible with 2.4.1 (2.4.1 available, latest is 2.5.0)

but it works fine now

**Comment by orif-jr** [comment]
I will close the issue for now as its resolved by croppie#2.5.0.
