### ISSUE TITLE
Rotate?

### ISSUE THREAD

**Issue by rizkyazhary** [allenRoyston/ngCroppie#4]
how to rotate image?

**Comment by quary1993** [comment]
https://raw.githubusercontent.com/quary1993/ngCroppie/6e980dc429913a5fbfd479cf6ebdc9fae3c5e109/src

In view:
	<ng-croppie   src="inputImage"
		  ng-model='outputImage'
		  update='onUpdate'
		  boundry="{w: 400, h: 400}"
		  viewport="{w: 300, h:300}"
		  mousezoom="true" 
		  zoom="true" 
		  enableOrientation="true"
  		  rotation="rotation"
		  type="circle">
	</ng-croppie>
        <button ng-click="rotateImage()" ><i class="fa fa-refresh"></i></button>
In controller:
 $scope.rotateImage=function(){
		// rotateBase64Image($scope.inputImage);
		$scope.rotation+=90; // 90 deg rotation
	  }

I added the rotation attribute. Bind it to a scope variable and you'll be able to rotate the canvas

**Comment by SoftAppLogic** [comment]
Hi,

included your new js file, but still not rotate the image. here i included my code. Please have a look and advice me anythink need to changed. Thanks

`<body ng-app="myApp">

    <div ng-controller="basicController">
        <div ng-controller="Ctrler">
            <label>Or upload your own: </label>
            <input id='fileInput' style='width: 400px' class='form-control' type='file' />

            

            <ng-croppie src="inputImage" 
                        ng-model="outputImage"
                        update='onUpdate'
                        boundry="{w: 400, h: 400}"
                        viewport="{w: 300, h:300}"
                        mousezoom="true"
                        zoom="true"
                        enableOrientation="true"
                        rotation="rotation"
                        type="circle">
            </ng-croppie>

            <a ng-click="rotateImage()">Rotate</a>

                

            <img ng-src="{{outputImage}}" />
</div>
        </div>

</body>

<script>

        var app = angular.module('myApp', ['ngCroppie']);

        app.controller('basicController', ['$scope', function ($scope) {

            $scope.inputImage = "images/Man.png";
            $scope.outputImage = null;

            var handleFileSelect = function (evt) {
                var file = evt.currentTarget.files[0];
                var reader = new FileReader();
                reader.onload = function (evt) {
                    $scope.$apply(function ($scope) {
                        $scope.inputImage = evt.target.result;
                    });
                };
                reader.readAsDataURL(file);
            };
           // angular.element(document.querySelector('#fileInput')).on('change', handleFileSelect);
            angular.element(document.querySelector('#fileInput')).on('change', handleFileSelect);
            $scope.onUpdate = function (data) {
                //console.log(data)
            }
        }]);

        app.controller('Ctrler', function ($scope) {
            $scope.rotateImage = function () {
                // rotateBase64Image($scope.inputImage);
                $scope.rotation += 90; // 90 deg rotation
                debugger;
            }
        })
    </script>`

**Comment by gozo77** [comment]
please initialise your $scope.rotation e.g.

$scope.inputImage = "images/Man.png";
$scope.outputImage = null;
$scope.rotation = 0;
...

**Comment by orif-jr** [comment]
@rizkyazhary, rotation functionality is included to version 1.0.0.
