### ISSUE TITLE
crop result broken

### ISSUE THREAD

**Issue by antoniocozianu** [allenRoyston/ngCroppie#40]
Sometimes, the base64 result of the crop is corrupted.
It looks something like this: 
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKoAAACqCAYAAAA9dtSCAAADLElEQVR4Xu3SAQ0AAAjDMO7fNDqWFAXP6M4pECiwwEYTFThQIUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28yUhQGUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28yUhQGUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28yUhQGUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28yUhQGUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28yUhQGUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28yUhQGUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28ycgH1oEAq7aSdTsAAAAASUVORK5CYII=

Does anyone know why?

**Comment by r3wt** [comment]
I am getting corrupt image as well.

**Comment by orif-jr** [comment]
@antoniocozianu can you please specify more details about your problem?

**Comment by orifn** [comment]
Closing the issue because of inactivity.
